name: "Tests"

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.5.9'
          bundler-cache: true
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel

  test:
    name: Automated test
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      INPUT_CHECK_JOB_NAME: simplecov
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.5.9'
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake spec
